[tool.poetry]
name = "project-generator"
version = "0.1.0"
description = ""
authors = [
    "zelkova <cohiba666@gmail.com>"
]
readme = "README.md"
packages = [{ include = "project_gen" }]

[tool.poetry.dependencies]
python = "^3.12.7"
cookiecutter = "^2.6.0"
requests = "^2.32.5"
toml = "^0.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
project_gen = "project_gen.main:cli"